// Dashboard components exports
export { default as StatisticsCards } from './statistics-cards'
export { default as AppointmentsDisplay } from './appointments-display'
export { default as PatientList } from './patient-list'
export { default as PatientDetails } from './patient-details'
export { AnalyticsCharts } from './analytics-charts'
export { PrescriptionManager } from './prescription-manager'
export { PrescriptionCreator } from './prescription-creator'
export { ConsultationDocumentation } from './consultation-documentation'
export { ConsultationNotes } from './consultation-notes'
export { ConsultationHistory } from './consultation-history'
export { DashboardErrorBoundary } from './dashboard-error-boundary'
export { OfflineIndicator } from './offline-indicator'
export { ErrorDisplay } from './error-display'